### ISSUE TITLE
Conflict with Google Analytics With Taplinx Library

### ISSUE THREAD

**Issue by legomanaustralia** [paypal/paypal-here-sdk-android-distribution#144]
We seem to be getting a conflict with paypal's version of google analytics and mifare "taplinx" google analytics. We're fairly certain GA is the root cause - is it possible to get a build of the newest library without the newer version of GA so we can confirm?

I've reached out to the taplinx folks to see if they can up-version their GA include in the interim. Have tried using transitive values for gradle for both to no avail.

**Comment by snehanshuashar** [comment]
@legomanaustralia we are working on removing some third-party dependencies from the PayPal Here sdk, and Google Analytics is one of those dependencies.
The next release of the PPH sdk (by the end of this month) should resolve your issue.

**Comment by legomanaustralia** [comment]
Oh perfect! happy to try out a beta build if you'd like? It was working perfectly but the last few changes have since broken the build for it so we've had to revert back before the tag option was available.

**Comment by snehanshuashar** [comment]
@legomanaustralia I just published a beta version of the sdk with these changes.
`2.0.1.201815-beta02`

**Comment by legomanaustralia** [comment]
@snehanshuashar thanks for that! Looks like we're still seeing a conflict, stemming from another library. There is an open ticket/issue so hopefully it'll be resolved, looks like the firebase changes are to blame. Will report back when they've got it resolved for anyone else that hits the same problem.

`releaseUnitTestCompileClasspath - Resolved configuration for compilation for variant: releaseUnitTest
+--- com.paypal.retail:here-sdk-debug:2.0.1.201815-beta02
|    +--- com.github.tony19:timber-loggly:1.0.1
|    |    +--- com.jakewharton.timber:timber:2.5.1
|    |    \--- com.github.tony19:loggly-client:1.0.3
|    |         +--- com.jakewharton.timber:timber:2.5.1
|    |         \--- com.squareup.retrofit:retrofit:1.9.0
|    |              \--- com.google.code.gson:gson:2.3.1 -> 2.8.2
|    +--- com.squareup.retrofit:retrofit:1.9.0 (*)
|    +--- com.android.support:appcompat-v7:26.1.0 -> 27.1.1
|    |    +--- com.android.support:support-annotations:27.1.1
|    |    +--- com.android.support:support-core-utils:27.1.1
|    |    |    +--- com.android.support:support-annotations:27.1.1
|    |    |    \--- com.android.support:support-compat:27.1.1
|    |    |         +--- com.android.support:support-annotations:27.1.1
|    |    |         \--- android.arch.lifecycle:runtime:1.1.0
|    |    |              +--- android.arch.lifecycle:common:1.1.0
|    |    |              \--- android.arch.core:common:1.1.0
|    |    +--- com.android.support:support-fragment:27.1.1
|    |    |    +--- com.android.support:support-compat:27.1.1 (*)
|    |    |    +--- com.android.support:support-core-ui:27.1.1
|    |    |    |    +--- com.android.support:support-annotations:27.1.1
|    |    |    |    +--- com.android.support:support-compat:27.1.1 (*)
|    |    |    |    \--- com.android.support:support-core-utils:27.1.1 (*)
|    |    |    +--- com.android.support:support-core-utils:27.1.1 (*)
|    |    |    +--- com.android.support:support-annotations:27.1.1
|    |    |    +--- android.arch.lifecycle:livedata-core:1.1.0
|    |    |    |    +--- android.arch.lifecycle:common:1.1.0
|    |    |    |    +--- android.arch.core:common:1.1.0
|    |    |    |    \--- android.arch.core:runtime:1.1.0
|    |    |    |         \--- android.arch.core:common:1.1.0
|    |    |    \--- android.arch.lifecycle:viewmodel:1.1.0
|    |    +--- com.android.support:support-vector-drawable:27.1.1
|    |    |    +--- com.android.support:support-annotations:27.1.1
|    |    |    \--- com.android.support:support-compat:27.1.1 (*)
|    |    \--- com.android.support:animated-vector-drawable:27.1.1
|    |         +--- com.android.support:support-vector-drawable:27.1.1 (*)
|    |         \--- com.android.support:support-core-ui:27.1.1 (*)
|    +--- com.eclipsesource.j2v8:j2v8:4.6.0
|    +--- com.squareup.okhttp:okhttp:2.3.0 -> 2.7.2
|    |    \--- com.squareup.okio:okio:1.6.0 -> 1.14.0
|    +--- com.google.code.gson:gson:2.8.0 -> 2.8.2
|    +--- com.google.android.gms:play-services-location:11.4.2
|    |    +--- com.google.android.gms:play-services-base:11.4.2
|    |    |    +--- com.google.android.gms:play-services-basement:11.4.2
|    |    |    |    +--- com.android.support:support-v4:25.2.0 -> 27.1.1
|    |    |    |    |    +--- com.android.support:support-compat:27.1.1 (*)
|    |    |    |    |    +--- com.android.support:support-media-compat:27.1.1
|    |    |    |    |    |    +--- com.android.support:support-annotations:27.1.1
|    |    |    |    |    |    \--- com.android.support:support-compat:27.1.1 (*)
|    |    |    |    |    +--- com.android.support:support-core-utils:27.1.1 (*)
|    |    |    |    |    +--- com.android.support:support-core-ui:27.1.1 (*)
|    |    |    |    |    \--- com.android.support:support-fragment:27.1.1 (*)
|    |    |    |    \--- com.google.android.gms:play-services-basement-license:11.4.2
|    |    |    +--- com.google.android.gms:play-services-tasks:11.4.2
|    |    |    |    +--- com.google.android.gms:play-services-basement:11.4.2 (*)
|    |    |    |    \--- com.google.android.gms:play-services-tasks-license:11.4.2
|    |    |    \--- com.google.android.gms:play-services-base-license:11.4.2
|    |    +--- com.google.android.gms:play-services-basement:11.4.2 (*)
|    |    +--- com.google.android.gms:play-services-tasks:11.4.2 (*)
|    |    \--- com.google.android.gms:play-services-location-license:11.4.2
|    +--- com.facebook.stetho:stetho-okhttp:1.5.0
|    |    +--- com.facebook.stetho:stetho:1.5.0
|    |    |    +--- commons-cli:commons-cli:1.2
|    |    |    \--- com.google.code.findbugs:jsr305:2.0.1 -> 1.3.9
|    |    +--- com.google.code.findbugs:jsr305:2.0.1 -> 1.3.9
|    |    \--- com.squareup.okhttp:okhttp:2.7.2 (*)
|    +--- com.paypal.instrumentation.facade:instrumentation-facade:0.0.3
|    \--- com.android.support.constraint:constraint-layout:1.1.0-beta3
|         \--- com.android.support.constraint:constraint-layout-solver:1.1.0-beta3
+--- taplinx-android:nxpnfcandroidlib:1.3
|    \--- com.google.android.gms:play-services-analytics:10.0.1
|         +--- com.google.android.gms:play-services-analytics-impl:10.0.1
|         |    +--- com.google.android.gms:play-services-base:10.0.1 -> 11.4.2 (*)
|         |    \--- com.google.android.gms:play-services-basement:10.0.1 -> 11.4.2 (*)
|         +--- com.google.android.gms:play-services-base:10.0.1 -> 11.4.2 (*)
|         +--- com.google.android.gms:play-services-basement:10.0.1 -> 11.4.2 (*)
|         \--- com.google.android.gms:play-services-tagmanager-v4-impl:10.0.1
|              +--- com.google.android.gms:play-services-analytics-impl:10.0.1 (*)
|              +--- com.google.android.gms:play-services-base:10.0.1 -> 11.4.2 (*)
|              \--- com.google.android.gms:play-services-basement:10.0.1 -> 11.4.2 (*)`

**Comment by legomanaustralia** [comment]
is it possible to get the location service support moved up to 15.0.1?

**Comment by nsinghal90** [comment]
@legomanaustralia Is the conflict due to com.google.android.gms:play-services-analytics-impl:10.0.1 module?

**Comment by legomanaustralia** [comment]
@nsinghal90 just confirming @anton8900 is on the same team :)

**Comment by DJ92** [comment]
Please re-open this if the problem still persists. I haven't heard back in a while on this.
